version: "3.8"

services:
  rc-opensearch:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: rc-opensearch:1.0
    container_name: rc-opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - plugins.security.disabled=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net
    volumes:
      - ./docker/opensearch-data:/usr/share/opensearch/data

networks:
  opensearch-net:
    driver: bridge